SELECT TOP (1000) [StockItemSK]
      ,[StockItemID]
      ,[StockItemName]
      ,[Brand]
      ,[Size]
      ,[ColorName]
      ,[UnitPrice]
  FROM [WWI_DataWarehouse].[dbo].[Dim_StockItem]
    SELECT COUNT(*)   FROM [WWI_DataWarehouse].[dbo].[Dim_StockItem]